### ISSUE TITLE
Blender 2.83.2 linux64

### ISSUE THREAD

**Issue by ivanfet** [snuq/SnuSlideshowGenerator#1]
Thanks for creating and offering your slide show generator. It is amazing!!

The SnuSlideshowGenerator doesn't work in my version of Blender - Blender 2.83.2 linux64 and Linux Mint 19.3. There seem to be a few different errors. 

 When I click " Create Slideshow Generator" I get this error.

Read prefs: /home/ivan/.config/blender/2.83/config/userpref.blend
found bundled python: /home/ivan/Documents/Ivan/Blender/blender-2.83.2-linux64/2.83/python
Importing video 1, filename: 0001-3458.mp4
Importing image 2, filename: IMG22854.jpg
Traceback (most recent call last):
  File "/home/ivan/.config/blender/2.83/scripts/addons/SnuSlideshowGenerator-Blender_2_81/__init__.py", line 2536, in execute
    last_image = import_slideshow_image(image, image_number, slide_length, generator_scene, video=is_video, last_image=last_image)
  File "/home/ivan/.config/blender/2.83/scripts/addons/SnuSlideshowGenerator-Blender_2_81/__init__.py", line 397, in import_slideshow_image
    add_constraints(target_empty, 'Target')
  File "/home/ivan/.config/blender/2.83/scripts/addons/SnuSlideshowGenerator-Blender_2_81/__init__.py", line 477, in add_constraints
    bpy.context.view_layer.objects.active = constraint_object
RuntimeError: Error: ViewLayer 'View Layer' does not contain object 'IMG22854.jpg Target'

After these errors, I tried SnuSlideshowGenerator in Blender-2.81a-linux-glibc217-x86_64 which I also have a copy installed. At first your Addin didn't work but I fiddled with it and it worked after a while. Don't know what made it work. I'm new to Blender and still learning the basics.

I just thought I would mention these errors as I have found your program made amazing videos once I worked out how to use it. Your instructions are very good but some of the advanced Extras I can't work out for now.
 Hopefully, it is a simple fix for you so it works in the latest version of Blender. Cheers Ivan

**Comment by snuq** [comment]
looks like this is caused by an api change in 2.83.  I have created a new release for blender 2.83, please download it and give it a shot.
